- hosts: all
  sudo: true
  remote_user: admin
  tasks:
  - name: Update cache
    apt: update_cache=yes

  - name: Instalar Git
    apt: name=git state=present

  - name: NGINX | Adding NGINX signing key
    apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
 
  - name: NGINX | Adding sources.list deb url for NGINX
    lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
 
  - name: NGINX Plus | Adding sources.list deb-src url for NGINX
    lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
 
  - name: NGINX | Updating apt cache
    apt:
      update_cache: yes
 
  - name: NGINX | Installing NGINX
    apt:
      pkg: nginx
      state: latest
 
  - name: NGINX | Starting NGINX
    service:
      name: nginx
      state: started

  - name: Install curl
    apt: name=curl

  - name: Install certificates apt https
    apt: name=apt-transport-https
    apt: name=ca-certificates

  - name: Clave docker
    shell: curl -fsSL https://yum.dockerproject.org/gpg | apt-key add -

  - name: Adding repositorio estable
    shell: add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-xenial  main"

  - name: Updating cache
    apt: update_cache=yes

  - name: Install docker engine
    apt: name=docker-engine

  - name: Download the container
    shell: docker pull stiago/debian-nginx

  
  
